# Generated by Django 2.1 on 2018-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20180817_1911'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='mainapp_per_name_063226_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['district'], name='mainapp_per_distric_4f7485_idx'),
        ),
    ]
