# Generated by Django 2.1 on 2018-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20180817_1911'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['district'], name='mainapp_req_distric_9b19c8_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requestee'], name='mainapp_req_request_2fe908_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requestee_phone'], name='mainapp_req_request_1d176b_idx'),
        ),
    ]
